<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAP1180" failures="1" tests="2" name="com.qa.tests.ProductTest" time="19.960" errors="0" timestamp="2022-05-24T16:51:20 UYT" skipped="0">
  <testcase classname="com.qa.tests.ProductTest" name="validateProductOnProductDetails" time="11.076"/>
  <system-out/>
  <testcase classname="com.qa.tests.ProductTest" name="validateProductOnProductPage" time="8.884">
    <failure message="The following asserts failed:
	expected [Sauce Labs Backpack] but found [Sauce Labs BackpackTest falla]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Sauce Labs Backpack] but found [Sauce Labs BackpackTest falla]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at com.qa.tests.ProductTest.validateProductOnProductPage(ProductTest.java:110)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:829)
]]>
    </failure>
  </testcase> <!-- validateProductOnProductPage -->
  <system-out>
    <![CDATA[This is the sample screeshot
<a href='C:\Users\clara.brizuela\Documents\Automation\Appium-TDDFramework\Screenshots\Android_pixel_3_\2022-05-24-16-50-45\ProductTest\validateProductOnProductPage.png'> <img src='C:\Users\clara.brizuela\Documents\Automation\Appium-TDDFramework\Screenshots\Android_pixel_3_\2022-05-24-16-50-45\ProductTest\validateProductOnProductPage.png' height='400' width='400'/> </a>]]>
  </system-out>
</testsuite> <!-- com.qa.tests.ProductTest -->
